### ISSUE TITLE
Některé tagy <DIV> nejsou uzavřený

### ISSUE THREAD

**Issue by Bebul** [snilekMatej/matejHtmlProjekt#7]
V Noteapad++ jsem si nechal spočítat, kolik je tam kterých `<div` a `</div` a jejich počet se liší.

Je potřeba, aby každý `<div>` měl k sobě zavírací `</div>`

 * `<div>` je **54x**
 * `</div>` jen **52x**

**Comment by snilekMatej** [comment]
mám to hotovo
